site_name: Formulaic

pages:

- [index.md, Introduction, Quickstart]

- [basic/forms.md, Basic usage, Create forms]
- [basic/validation.md, Basic usage, Validation]
- [basic/rendering.md, Basic usage, Custom rendering]

- [advanced/select.md, Advanced topics, Select boxes]

- [api/form.md, API reference, Form]
- [api/get.md, API reference, Get]
- [api/post.md, API reference, Post]
- [api/select.md, API reference, Select]

theme: readthedocs
