site_name: Formulaic

pages:
- Home: 'index.md'
- Basic usage:
    - 'Create forms': 'basic/forms.md'
    - 'Validation': 'basic/validation.md'
    - 'Custom rendering': 'basic/rendering.md'
    - 'Select boxes': 'basic/select.md'
- Advanced topics:
    - 'Handling complex arrays': 'advanced/arrays.md'
    - 'Groups of checkboxes or radio buttons': 'advanced/checkboxes.md'
    - 'Bitflag fields': 'advanced/bitflags.md'
- API reference:
    - 'Forms': 'api/forms.md'
    - 'Elements': 'api/elements.md'
    - 'Buttons': 'api/buttons.md'
    - 'Traits': 'api/traits.md'

theme: readthedocs
